### ISSUE TITLE
Support for winston 1.0.0

### ISSUE THREAD

**Issue by chmac** [winstonjs/winston-loggly#26]
When I try to install winston-loggly 1.0.5 I get the following:

    npm ERR! peerinvalid The package winston does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer winston-loggly@1.0.5 wants winston@0.x.x

It looks like winston has gone 1.0.0 and this package doesn't support it.

I was able to workaround by installing winston 0.9.0 instead.

**Comment by indexzero** [comment]
Fixed in `winston-loggly@1.1.0`. We removed the `peerDependencies` all together.

**Comment by chmac** [comment]
Awesome, thanks. Now we can run the latest winston-loggly. :+1:
