### ISSUE TITLE
The content of a prop named `message` will not be submitted.

### ISSUE THREAD

**Issue by despairblue** [winstonjs/winston-loggly#43]
```js
winston.info({
  message: 'hey',
  msg: 'ho'
})
```

This will log `{"message": "", "msg": "ho"}` to loggly. The console output will be correct, so I suppose this is a bug in the transport and a **super** weird one.

By the way, is anyone maintaining this library? It seems there are a lot of open issues with no real progress.

**Comment by framerate** [comment]
I'm not maintaining this but I've contributed before. The code was fairly straightforward I believe so you could probably track this down easily.

**Comment by despairblue** [comment]
I switched to log4js now. sry :/

On Wed, Apr 6, 2016, 20:56 Justin Reynard <notifications@github.com> wrote:

> I'm not maintaining this but I've contributed before. The code was fairly
> straightforward I believe so you could probably track this down easily.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/winstonjs/winston-loggly/issues/43#issuecomment-206513006>
>
-- 
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by krazik** [comment]
it's trivial to track down.  just create a log with the json key 'message'.   how is this not impacting everyone?  I've switched the official winston-loggly-bulk plugin w/ better results.

**Comment by krazik** [comment]
lol not gonna fix it?

**Comment by indexzero** [comment]
Apologies. This is a duplicate.
