### ISSUE TITLE
loggly.log("message", undefined) breaks

### ISSUE THREAD

**Issue by valeriansaliou** [winstonjs/winston-loggly#49]
Noticed that since November update, loggly.log("message", error) when error=undefined breaks where it shouldn't (I guess).

Offending line: https://github.com/winstonjs/winston-loggly/blob/ff56088b4cf76fd00724ebab3cfe37f2ab66276a/lib/winston-loggly.js#L116

See related issue on Winston: https://github.com/winstonjs/winston/issues/947

Can PR if you confirm.

**Comment by phouverneyuff** [comment]
Same error here!

**Comment by Besiara** [comment]
Same issue!

**Comment by sirgalleto** [comment]
Is this issue really still open?

**Comment by grantcarthew** [comment]
There is a PR @sirgalleto as you can see. The maintainers just need to spend some time on it. Time is precious we all know, however maybe somebody from the loggly company should get involved seeing as they get paid for their time.

**Comment by sirgalleto** [comment]
I understand. I hope to have the review soon.

**Comment by valeriansaliou** [comment]
Thanks @grantcarthew for the PR — hope we can get this merged soon and published to NPM. 👍

**Comment by roshanpaiva** [comment]
+1
