### ISSUE TITLE
 Inquiry about winston-loggly Maintenance Status

### ISSUE THREAD

**Issue by walosha** [winstonjs/winston-loggly#64]
Hello,

I hope this message finds you well. I'm a user of Loggly and I'm interested in understanding the current maintenance status of the Loggly service. I've noticed some concerns in the community regarding updates and support, and I wanted to reach out to the maintainers directly to seek clarification.

Specifically, I have the following questions:

Is Loggly actively maintained, and can users expect updates and bug fixes in the foreseeable future?
Are there any planned updates, improvements, or changes to Loggly's features or infrastructure?
How can users contribute or get involved in the development and maintenance of Loggly if they are interested?
I believe that many users, including myself, would greatly appreciate some insight into the current state and future plans for Loggly. Your response will help us make informed decisions about its usage in our projects.

Thank you for your time, and I look forward to hearing from you.

**Comment by DABH** [comment]
If you are asking about Loggly itself, you should contact SolarWinds support https://www.loggly.com/ .  This repository is only about the Winston transport for Loggly.  I’m going to close this issue since it sounds like you’re asking about Loggly, but if you are asking about Winston, feel free to re-open.  Thanks!

**Comment by walosha** [comment]
i meant winston-loggly. sorry for the miss up @DABH

**Comment by wbt** [comment]
The questions above are a lot more about the Loggly service than the Winston connector to it, though.

**Comment by DABH** [comment]
As far as `winston-loggly` goes, there is no one actively driving development right now, but users are more than welcome to contribute PRs, especially ones that help increase testing and compatibility guarantees while also adding new features.  We (the core winston team) are happy to help with releases and reviewing PRs, although our very limited time is primarily focused on winston core.

In particular, there are no system tests that verify whether `winston-loggly` works with the current latest version of Loggly, and that's something that would probably be very useful...
